services:
  mongo:
    image: mongo
    volumes:
      - './data:/data/db/'
    ports:
      - 27017:27017
  spring:
    build: ./ECF4
    ports:
      - 8080:8080
    depends_on:
      - mongo
    restart: always
  front:
    build: ./ECF3Bis
    ports:
      - 3000:3000